FAi-678 DfESignIn NuGet
SkillsFundingAgency/das-shared-packages pull request #655
Opened 2022-11-07 13:35 UTC by alireid

2022-11-08 18:05 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Helpers/JsonWebAlgorithmTests.cs
> +            this.mockRepository = new MockRepository(MockBehavior.Strict);
no `this`

2022-11-08 18:08 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Client/DfESignInClientFactory.cs
> +            var dsiConfiguration = _config.GetSection("DfEOidcConfiguration").Get<DfEOidcConfiguration>();
i would have thought we could have just resolved the config in the DI rather than doing this?

2022-11-08 18:08 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Client/DfESignInClientFactory.cs
> +            var dfeSignInClient = new DfESignInClient(new HttpClient())
dont really want to be new'ing up the HttpClient - this should be injected

2022-11-08 18:11 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Client/DfESignInClientFactory.cs
> +            dfeSignInClient.HttpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
using the DefaultRequestHeader is not thread safe and you risk having multiple headers added. Should also be doing:
```
.Authorization = new AuthenticationHeaderValue("Bearer", token);
```

2022-11-08 18:12 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Client/DfESignInClientFactory.cs
> +            var token = new TokenBuilder(new TokenDataSerializer(), tokenData, new TokenEncoder(), new JsonWebAlgorithm())
This seems like a lot of new that is wrong all this should be injected?

2022-11-08 18:14 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Helpers/TokenBuilder.cs
> +        public ITokenData TokenData { get; set; }
Shouldn't this be private?

2022-11-08 18:15 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Helpers/TokenBuilder.cs
> +            return token;
I feel like this is missing test coverage

2022-11-08 18:16 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Helpers/TokenBuilderExtensions.cs
> +        public static TokenBuilder ForAudience(this TokenBuilder tokenBuilder, string audience)
I think this should be TokenData extensions rather than TokenBuilder and expose the insides

2022-11-08 18:17 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs
> +            services.AddTransient(typeof(ICustomClaims), customClaims);
Not sure we need CustomClaims for this one? it looks like its only used in the stub

2022-11-08 18:17 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Configuration/DfEOidcConfiguration.cs
> +    public interface IDfEOidcConfiguration
Do we need this?

2022-11-08 18:18 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ProviderStubAuthHandler.cs
> +            return result;
this probably needs to be more geared towards provider auth, adding the ukprn and necessary role

2022-11-08 18:20 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs
> +            await DfEPublicApi(ctx, userId, userOrganisation.Id.ToString(), config);
i feel like this should be injected rather than new'd up inside the method

2022-11-09 08:04 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Client/DfESignInClientFactoryTests.cs
> +        private MockRepository mockRepository;
Good spot, thanks Dan, fixed those up

2022-11-09 08:06 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Client/DfESignInClientFactoryTests.cs
> +            this.mockRepository = new MockRepository(MockBehavior.Strict);
Good spot, thanks Dan, fixed those up

2022-11-09 08:07 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Client/DfESignInClientFactoryTests.cs
> +            var factory = this.CreateFactory();
Agreed, removed!

2022-11-09 08:07 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Helpers/JsonWebAlgorithmTests.cs
> +        private MockRepository mockRepository;
Fixed up those, thanks

2022-11-09 08:08 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Helpers/JsonWebAlgorithmTests.cs
> +            this.mockRepository = new MockRepository(MockBehavior.Strict);
Thanks Dan, removed all those

2022-11-09 08:10 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Configuration/DfEOidcConfiguration.cs
> +    public interface IDfEOidcConfiguration
Agreed, surplus! Removed, thanks

2022-11-09 08:12 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs
> +            services.AddTransient(typeof(ICustomClaims), customClaims);
Discovered this one when I included it another project, good shout, thanks, removed!

2022-11-09 08:19 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Client/DfESignInClientFactory.cs
> +            dfeSignInClient.HttpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
Nice, fixed that up

2022-11-09 08:19 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Configuration/DfEOidcConfigurationTests.cs
> +            Assert.That(dfEOidcConfiguration, Is.Not.Null);
Ha yes, agreed, nuked!

2022-11-09 08:20 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Helpers/JsonWebAlgorithmTests.cs
> +        private JsonWebAlgorithm CreateJsonWebAlgorithm()
Thanks Dan, agreed, cleaned up that up

2022-11-09 15:49 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Client/DfESignInClientFactory.cs
> +            var dsiConfiguration = _config.GetSection("DfEOidcConfiguration").Get<DfEOidcConfiguration>();
Good spot Dan, not sure why that was left like that as config all ready fired up in DI. Fixed up, thanks.

2022-11-10 09:08 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs
> +            await DfEPublicApi(ctx, userId, userOrganisation.Id.ToString(), config);
Thanks Dan, nice - got that in

2022-11-10 11:31 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ProviderStubAuthHandler.cs
> +            return result;
Thanks Dan, didn't know what claims were needed until first implementation, added in now.

2022-11-10 12:21 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Helpers/JsonWebAlgorithmTests.cs
> +            Assert.That(result, Is.Not.Null);
Correct, thanks

2022-11-11 09:16 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Helpers/TokenBuilder.cs
> +            return token;
Agreed there Dan, thanks, didn't spent too much time with the unit tests, adding a load in now

2022-11-11 10:32 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Api/Client/DfESignInClientFactoryTests.cs
> +            // Assert
Thanks Dan, agreed, working on unit test now - added a load in

2022-11-16 08:09 UTC, dashton82 requested changes

2022-11-16 08:09 UTC, dashton82 commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs
> +            Type customClaims)
This can be removed as it isn't used anymore

2022-11-16 17:34 UTC, scottywakefield reviewed
Hi @alireid, could you please use cdn sources for the libs in the sample site plz, will remove about 39,000 lines of code from the PR and the repo.

2022-11-17 08:59 UTC, alireid commented
> Hi @alireid, could you please use cdn sources for the libs in the sample site plz, will remove about 39,000 lines of code from the PR and the repo.

Hi @scottywakefield - great shout, removed and added cdns.

2022-11-17 09:10 UTC, alireid commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Interfaces/IDfESignInClient.cs
> +    public interface IDfESignInClient
Agreed, surplus, removed

2022-11-25 09:22 UTC, balaji-j commented on SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Helpers/TokenBuilderExtensions.cs
> +        public static TokenBuilder ForAudience(this TokenBuilder tokenBuilder, string audience)
Hi Dan, As per PR recommendations I have modified the code base and these are the modifications below 

1) Renamed file TokenBuilderExtension to TokenDataExtensions
2) Amended Exception messages to appropriate ones
3) Included Unit Test cases to cover the logic under TokenDataExtensions

2022-12-09 11:09 UTC, merged